bfg/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('landing.urls')),
]

store/courier/urls.py
from django.conf.urls import url
import store.courier.views as views

urlpatterns = [
    url(r'^get_rate$', views.get_rate, name='courier_get_rate'),
    url(r'^get_shipment$', views.get_rate, name='courier_get_shipment'),
    url(r'^hooks$', views.webhooks, name='webhooks'),
]

store/payment/urls.py
from django.conf.urls import url, include
from django.contrib import admin

import store.payment.views as views

urlpatterns = [
    url(r'^order/(?P<random>\w+)/$', views.pay_order, name="pay_order"),
    url(r'^payment/(?P<payment_id>\d+)$', views.payment_details, name="pay_payment"),
    url(r'^result/(?P<token>[0-9a-z]{8}-[0-9a-z]{4}-[0-9a-z]{4}-[0-9a-z]{4}-[0-9a-z]{12})/$', views.pay_result,
        name="result"),
    url(r'^paynow/$', views.pay_begin, name="payment_now"),
    url(r'^result/(?P<code>\w+)/$', views.pay_server_result, name="payment_server_result"),
    url(r'^secret/(?P<code>\w+)/(?P<id>\d+)$', views.pay_secret, name="payment_secret"),
    url(r'^plan_promo/$', views.plan_prom, name="payment_plan_promos"),
    url(r'^plan_price/$', views.plan_price, name="payment_plan_price"),
]

store/urls.py
# noinspection PyPackageRequirements
from django.conf.urls import url, include
# noinspection PyPackageRequirements
from django.contrib import admin
import store.views as views

urlpatterns = [
    url(r'^$', views.index, name="home"),
    url(r'^courier/', include('store.courier.urls', namespace='courier')),
    url(r'^category$', views.category, name="category_root"),
    url(r'^product/(?P<id>\d+).html$', views.product, name="product_detail"),
    url(r'^plan/(?P<id>\d+).html$', views.plan_detail, name="plan_detail"),
    url(r'^cart/$', views.cart, name="cart"),
    url(r'^cart/add_plan/(?P<id>\d+)/$', views.cart_add_plan, name="cart_add_plan"),
    url(r'^cart/add_product/(?P<id>\d+)/$', views.cart_add_product, name="cart_add_product"),
    url(r'^wishlist/add_product/(?P<id>\d+)/$', views.cart, name="wishlist_add_product"),
    url(r'^checkout/$', views.checkout, name="checkout"),
    url(r'^checkout_result/$', views.checkout_result, name="store_checkout_result"),
    url(r'^pay/', include('store.payment.urls', namespace="pay")),
    url(r'^admin_change_plan/$', views.admin_change_plan, name="store_admin_change_plan"),
    url(r'^admin_confirm_plan/(?P<id>\d+)$', views.admin_confirm_plan, name="store_admin_confirm_plan"),
    url(r'^admin_pay_order/(?P<id>\d+)$', views.admin_pay_order, name="store_admin_pay_order"),
    url(r'^admin_pay_result/(?P<id>\d+)$', views.admin_pay_result, name="store_admin_pay_result"),
    url(r'^account/order/list/$', views.account_order_list, name="account_order_list"),
    url(r'^account/order/list/(?P<id>\d+)$', views.account_order_view, name="account_order_view"),
    url(r'^account/payment/list/$', views.account_payment_list, name="account_payment_list"),
    url(r'^my/$', views.checkout, name="store_myaccount"),
]

appa/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth import models as AdminModels
from ckeditor_uploader.fields import RichTextUploadingField
from django.utils.translation import gettext_lazy as _
from django.db import models
from landing.models import Variable


# Create your models here.
class Company(models.Model):
    title = models.CharField(max_length=100)
    code = models.CharField(max_length=10, unique=True, default=None, null=True, blank=True)
    administrator = models.ForeignKey('Staff', null=True, blank=True, default=None, related_name='administrator',
                                      on_delete=models.SET_DEFAULT)
    staffs = models.ManyToManyField('Staff', related_name="staffs", blank=True, default=None)
    variables = models.ManyToManyField(Variable, related_name="variables", blank=True, default=None)
    tax_number = models.CharField(max_length=50, default=None, null=True, blank=True)
    tax_name = models.CharField(max_length=10, default='GST', blank=True)
    tax_rate = models.FloatField(default=0, blank=True)
    bank_account = models.CharField(max_length=50, default=None, null=True, blank=True)
    bank_account_name = models.CharField(max_length=50, default=None, null=True, blank=True)
    bank_name = models.CharField(max_length=100, default=None, null=True, blank=True)
    size_level = models.CharField(max_length=1, default=None, null=True, blank=True)
    stripe_account = models.CharField(max_length=50, default=None, null=True, blank=True)
    paypal_account = models.CharField(max_length=50, default=None, null=True, blank=True)

    qr_check = models.BooleanField(default=True)
    confirm_email = models.BooleanField(default=True)
    email_as_username = models.BooleanField(default=False)

    last_active = models.DateTimeField(auto_now=True)
    settings = models.TextField(default=None, null=True, blank=True)
    active_index = models.PositiveIntegerField(default=0)
    logo = models.ImageField(blank=True, null=True, default=None)
    lat = models.FloatField(default=0)
    lng = models.FloatField(default=0)
    credit = models.PositiveIntegerField(default=0)
    used_credit = models.PositiveIntegerField(default=0)
    feedback_rate = models.FloatField(default=0)
    content = RichTextUploadingField(null=True, default=None, blank=True)
    terms = RichTextUploadingField(null=True, default=None, blank=True)
    invoice_terms = RichTextUploadingField(null=True, default=None, blank=True)
    privacy = RichTextUploadingField(null=True, default=None, blank=True)
    homepage = models.CharField(max_length=500, null=True, default=None, blank=True)

    account_facebook = models.CharField(max_length=50, default=None, null=True, blank=True)
    account_googleplus = models.CharField(max_length=50, default=None, null=True, blank=True)
    account_twitter = models.CharField(max_length=50, default=None, null=True, blank=True)
    account_instgram = models.CharField(max_length=50, default=None, null=True, blank=True)
    account_pintrest = models.CharField(max_length=50, default=None, null=True, blank=True)
    account_wechat = models.CharField(max_length=50, default=None, null=True, blank=True)
    account_qq = models.CharField(max_length=50, default=None, null=True, blank=True)

    mail_account = models.ForeignKey('MailAccount', default=None, null=True, blank=True, on_delete=models.SET_DEFAULT,
                                     related_name="main_mailaccount")
    mail_header = RichTextUploadingField(default=None, null=True, blank=True)
    mail_footer = RichTextUploadingField(default=None, null=True, blank=True)

    def get_variable_list(self):
        return [
            {'key': 'private_policy', 'value': None, 'description': 'Privacy Policy'},
            {'key': 'terms', 'value': None, 'description': 'Terms and Conditions'},
        ]

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _("Company")
        verbose_name_plural = _("Companies")


class CompanyModelBase(models.Model):
    company = models.ForeignKey(Company, null=True, blank=True, default=None, on_delete=models.SET_DEFAULT)

    class Meta:
        abstract = True


class Printer(CompanyModelBase):
    title = models.CharField(max_length=50, null=True, blank=True, default=None)
    sn = models.CharField(max_length=32)
    username = models.CharField(max_length=100)
    password = models.CharField(max_length=200)
    server = models.CharField(max_length=100)
    gap = models.SmallIntegerField(default=2)
    width = models.SmallIntegerField(default=40)
    length = models.SmallIntegerField(default=50)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _("Printer")
        verbose_name_plural = _("Printers")


class Staff(AdminModels.User):
    company = models.ForeignKey(Company, null=True, blank=True, default=None, related_name='appa_staff_company',
                                on_delete=models.SET_DEFAULT)
    title = models.CharField(max_length=30, null=True, blank=True, default=None)
    printer = models.ForeignKey(Printer, default=None, null=True, blank=True, on_delete=models.SET_DEFAULT)

    def in_group(self, group_name):
        return self.groups.filter(name=group_name).exists()

    def __str__(self):
        return self.title if self.title else self.get_full_name()

    class Meta:
        verbose_name = _("Staff")
        verbose_name_plural = _("Staffs")


DeviceType = (
    ("I", "iOS"),
    ("A", "Amdrpod"),
)


class Device(models.Model):
    title = models.CharField(max_length=50, null=True, blank=True, default=None)
    user = models.ForeignKey(AdminModels.User, null=True, blank=True, default=None, on_delete=models.CASCADE)
    device_id = models.CharField(max_length=100, null=True, blank=True, default=None)
    enable = models.BooleanField(default=True)
    type = models.CharField(max_length=1, default='I', choices=DeviceType)
    last_login = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = _("Device")
        verbose_name_plural = _("Devices")


MailAccountType = (
    ("landing.core.mail.SmtpMailProvider", "Smtp Client"),
    ("landing.core.mail.MailGunMailProvider", "MailGun Client"),
)


class MailAccount(CompanyModelBase):
    cls = models.CharField(max_length=50, null=True, blank=True, default=None, choices=MailAccountType)
    server = models.CharField(max_length=50, null=True, blank=True, default=None)
    user = models.CharField(max_length=50, null=True, blank=True, default=None)
    password = models.CharField(max_length=50, null=True, blank=True, default=None)
    port = models.PositiveIntegerField(default=465, blank=True)
    ssl = models.BooleanField(default=True, blank=True)
    url = models.CharField(max_length=250, null=True, blank=True, default=None)
    key = models.CharField(max_length=250, null=True, blank=True, default=None)


MailTemplateType = (
    ("M", "Mail"),
    ("WXAPP", "Wechat App"),
    ("IM", "Internal Message"),

)


class CompanyMailTemplate(CompanyModelBase):
    lang = models.CharField(max_length=10, default=None, null=True, blank=True)
    key = models.CharField(max_length=50, default=None, null=True,
                           help_text='Template identifier. Must be unique.')
    subject = models.CharField(max_length=200, default=None, null=True)
    body = RichTextUploadingField(default=None, null=True, blank=True)
    type = models.CharField(max_length=5, default=None, null=True, blank=True)
    is_html = models.BooleanField(default=True, blank=True)
    last_sync_time = models.DateTimeField(default=None, null=True, blank=True)
    enable = models.BooleanField(default=True, blank=True)

    class Meta:
        unique_together = ('company', 'lang', 'key')
        verbose_name = _("Mail Template")
        verbose_name_plural = _("Mail Templates")

appa/controllers/company.py
# noinspection PyPackageRequirements
import qrcode
import os
from django.db import transaction
from django.shortcuts import render, reverse
from landing.core.common import get_action_result, get_req_value, check_dir
from django.utils.crypto import get_random_string
from django.db.models import Q
from bfg.appa.models import *
from store.models import *
from bfg.appa.controllers.core import *


class AppaCompanyManager(object):
    def __init__(self, request=None):
        self.request = request

    def create_company(self, data):
        # Create the company
        company = Company()
        company.title = data['title']
        company.save()

    def get_company(self, id=0):
        if id == 0:
            return get_staff_company(self.request)
        else:
            try:
                return get_company_class().objects.get(id=id)
            except:
                return None

    def get_company_by_homepage(self):
        '''
        Find Company from headers in Wechat App Access
        :param use_default:
        :return:
        '''
        company = None
        if self.request:
            if 'HTTP_ORIGIN' in self.request.META:
                host = self.request.META['HTTP_ORIGIN']
                qs = get_company_class().objects.filter(homepage__icontains=host)
                if qs.exists():
                    company = qs.first()
            elif 'HTTP_HOST' in self.request.META:
                host = self.request.META['HTTP_HOST']
                qs = get_company_class().objects.filter(homepage__icontains=host)
                if qs.exists():
                    company = qs.first()
        return company

    def set_company(self, company):
        if not company:
            company = get_staff_company(self.request)
        return company

    def get_staffs(self, company=None):
        company = self.set_company(company)
        return Staff.objects.filter(company=company)

    def get_files(self, path):
        from os import listdir
        from os.path import isfile, join
        files = [f for f in listdir(path) if isfile(join(path, f))]
        return files

    def sync_mail_template(self, template_path):
        filename = os.path.basename(template_path)
        parts = os.path.splitext(filename)
        if len(parts) == 2 and parts[1] == '.html':
            filenames = parts[0].split('-')

    def send_resetpwd_mail(self, email):
        from landing.core.account import Account
        if self.request.user.is_authenticated:
            customer = self.request.user
        else:
            customers = AdminModels.User.objects.filter(email=email)
            if customers.exists():
                customer = customers.first()
            else:
                raise Exception('User not found.')
        am = Account(self.request)
        am.send_resetpwd_email(customer, mail_account=self.get_mail_account())
        return True

    def get_mail_account(self, company=None):
        if not company:
            company = self.get_company_by_homepage()
        else:
            if not isinstance(company, Company):
                raise Exception('Company is not available')
        if company and company.mailaccount_set.exists():
            return company.mailaccount_set.first()
        else:
            settings = get_bfg_settings('mail')
            return MailAccount(cls=settings['provider'],
                               url=settings['settings']['url'],
                               key=settings['settings']['key'],
                               user=settings['settings']['sender'])

    def get_customer(self, id):
        try:
            return Customer.objects.get(id=id)
        except:
            return None

    def get_variable(self, company, key):
        key = key.upper()
        try:
            variable = company.variables.get(key=key)
            return variable.content
        except:
            return None

appa/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.conf import settings
from bfg.appa.controllers.core import get_staff_company

# Create your views here.
@login_required(login_url='/login/')
def index(request):
    return render(request, 'appa/index.html')

@login_required()
def sidebar(request):
    # pm = PlanManager(request)
    # profile = get_user_profile(request)
    company = get_staff_company(request)
    # plan = pm.get_user_plan(company.administrator)
    # is_admin = is_user_admin(request,company)
    site = settings.APPA_SITE
    return render(request, 'appa/includes/sidebar.html', locals())

store/courier/views.py
from django.http import JsonResponse,HttpResponseServerError
from store.courier.core.freights import CourierManager
from bfg.appa.core.common import *
from landing.core.common import *
from django.views.decorators.csrf import csrf_exempt
import json



def get_rate(request):
    address = json.loads(request.POST.get('body'))
    fm = CourierManager()
    token = company_account.account
    admin = fm.get_feight_admin(company_account.type,token)
    result = admin.get_rates(address)
    return JsonResponse(result,safe=False)

def get_shipment(request):
    if request.method == 'POST':
        if 'body' in request.POST:
            address = json.loads(request.POST.get('body'))
            company_id = get_user_company_id(request)
            fm = CourierManager()
            company_account = __get_company_account(fm, company_id, request)
            token = company_account.account
            admin = fm.get_feight_admin(company_account.type, token)
            return JsonResponse(admin.create_shipment(address))
        else:
            raise ValueError('body can not be found in POST')
    elif request.method == 'DELETE':
        pass
    else:
        pass

@csrf_exempt
def webhooks(request):
    account = get_req_value(request, "account")
    cm = CourierManager(request)
    account = cm.get_courier_account_by_account_id(account_id=account)
    courier = get_class_by_path(account.type)(request)
    courier.process_hook_request(request)
    return HttpResponse('Process webhooks successfully')

store/templates/store/appa/bank_statement_list_buttons.html
{% load i18n landing_tags static %}
<button class="btn btn-default submit-btn" data-action="{% url 'appa:store_bankstatement_action' %}?action=match" refresh="page" type="button" >{% trans 'Match' %}</button>
<form class="pull-right" enctype="multipart/form-data"
   action="{% url 'appa:store_bankstatement_action' %}?{{ request.GET.urlencode|url_remove_param:'o' }}&action=import" method="post"
   style="margin-left: 15px">
    {% csrf_token %}
    <input type="file" style="position: absolute; top: -1000px" name="file">
    <button class="btn btn-success import_file" type="button" >{% trans 'Import' %}</button>
    <input type="checkbox" name="import_extra" checked > {% trans 'Only Import New Records' %}
</form>

store/templates/store/appa/product_discount.html
{% extends 'store/appa/master/product_layout.html' %}
{% load i18n static landing_tags %}

{% block content_section %}
<section class="tab-pane active" id="basic">
    <section class="panel">
        <header class="panel-heading font-bold">
            {% trans 'Discounts' %}
        </header>
        <div class="panel-body">
            <form class="form-horizontal" method="post">
                {% csrf_token %}
                <div class="line line-dashed line-lg pull-in"></div>
                <div class="form-group">
                    <div class="col-sm-4 col-sm-offset-2">
                        <button type="submit" name="action" value="save" class="submit_edit btn btn-primary">{% trans 'Save changes' %}</button>
                        <button type="button" class="btn btn-white btn-cancel">{% trans 'Cancel' %}</button>
                    </div>
                </div>
            </form>
        </div>
    </section>
</section>
{% endblock %}

{% block product_js %}
    <script>
        $(function () {

        });
    </script>
{% endblock %}

store/templates/store/appa/product_rules.html
{% extends 'store/appa/master/product_layout.html' %}
{% load i18n static landing_tags %}

{% block content_section %}
<section class="tab-pane active" id="basic">
    <section class="panel">
        <header class="panel-heading font-bold">
            {% trans 'Rules' %}
        </header>
        <div class="panel-body">
            <form class="form-horizontal" method="post">
                {% csrf_token %}
                <div class="line line-dashed line-lg pull-in"></div>
                <div class="form-group">
                    <div class="col-sm-4 col-sm-offset-2">
                        <button type="submit" name="action" value="save" class="submit_edit btn btn-primary">{% trans 'Save changes' %}</button>
                        <button type="button" class="btn btn-white btn-cancel">{% trans 'Cancel' %}</button>
                    </div>
                </div>
            </form>
        </div>
    </section>
</section>
{% endblock %}

{% block product_js %}
    <script>
        $(function () {

        });
    </script>
{% endblock %}

store/templates/store/appa/product_seo.html
{% extends 'store/appa/master/product_layout.html' %}
{% load i18n static landing_tags %}

{% block content_section %}
<section class="tab-pane active" id="basic">
    <section class="panel">
        <header class="panel-heading font-bold">
            {% trans 'SEO' %}
        </header>
        <div class="panel-body">
            <form class="form-horizontal" method="post">
                {% csrf_token %}
                <div class="line line-dashed line-lg pull-in"></div>
                <div class="form-group">
                    <div class="col-sm-4 col-sm-offset-2">
                        <button type="submit" name="action" value="save" class="submit_edit btn btn-primary">{% trans 'Save changes' %}</button>
                        <button type="button" class="btn btn-white btn-cancel">{% trans 'Cancel' %}</button>
                    </div>
                </div>
            </form>
        </div>
    </section>
</section>
{% endblock %}

{% block product_js %}
    <script>
        $(function () {

        });
    </script>
{% endblock %}

store/templates/store/appa/product_variants.html
{% extends 'store/appa/master/product_layout.html' %}
{% load i18n static landing_tags %}

{% block content_section %}
<section class="tab-pane active" id="basic">
    <section class="panel">
        <header class="panel-heading font-bold">
            {% trans 'Variants' %}
        </header>
        <div class="panel-body">
            <form class="form-horizontal" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label class="col-sm-2 control-label">{% trans 'Name' %}</label>
                    <div class="col-sm-10">
                        <input name="title" type="text"
                               class="form-control"
                               placeholder="Product name"
                               maxlength="300"
                               value="{{ product.title }}" required>
                    </div>
                </div>
                <div class="form-row field-height">
                    <div class="form-group">
                        <label class="required control-label col-sm-2"
                               for="id_height">{% trans 'Variant List' %}:</label>
                        <div class="col-sm-1">
                            {% trans 'Title' %}
                        </div>
                        <div class="col-sm-3">
                            {% trans 'Content' %}
                        </div>
                        <div class="col-sm-1">
                            {% trans 'Quantity' %}
                        </div>
                        <div class="col-sm-1">
                            {% trans 'SKU' %}
                        </div>
                        <div class="col-sm-1">
                            {% trans 'Image' %}
                        </div>
                    </div>
                    {% if product.variants.all|length > 0 %}
                        {% for piece in parcel.parcelpiece_set.all %}
                            <div class="form-group parcel_row">
                                <input type="hidden" name="piece_ids" value="{{ piece.id }}">
                                <div class="col-sm-1 col-sm-offset-2">
                                    <input type="number" name="piece_length"
                                           value="{{ piece.length|zero_default:0 }}" step="any"
                                           min="1"
                                           required="" class="form-control length" id="id_length">
                                </div>
                                <div class="col-sm-3">
                                    <input type="number" name="piece_height"
                                           value="{{ piece.height|zero_default:0 }}" step="any"
                                           min="1"
                                           required="" class="form-control height" id="id_height">
                                </div>
                                <div class="col-sm-1">
                                    <input type="number" name="piece_width"
                                           value="{{ piece.width|zero_default:0 }}" step="any"
                                           min="1"
                                           required="" class="form-control width" id="id_width">
                                </div>
                                <div class="col-sm-1">
                                    <input type="number" name="piece_weight"
                                           value="{{ piece.weight|zero_default:0 }}" step="0.01"
                                           min="0.1"
                                           required="" class="form-control weight" id="id_weight">
                                </div>
                                <div class="col-sm-1">
                                    <label class="checkbox-inline">
                                        <input type="checkbox" class="times"
                                               {% if piece.times %}checked{% endif %}> x
                                        <input type="hidden" name="is_whole" value="off">
                                    </label>
                                </div>
                                <div class="col-sm-1">
                                    <input type="number" name="piece_quantity"
                                           value="{{ piece.quantity|zero_default:1 }}" step="any"
                                           min="1"
                                           required="" class="form-control quantity" id="id_quantity">
                                </div>
                                <div class="col-sm-1">
                                    <select name="piece_wrapping_type" id="id_wrapping_type" required=""
                                            class="form-control"
                                            selected_id="{% cookie piece.wrapping_type_id 'WrappingType' %}">
                                        <option value="">---------</option>
                                        {% for wrapping_type in wrapping_types %}
                                            <option value="{{ wrapping_type.id }}">{% trans wrapping_type.title %}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                                <div class="col-sm-2">
                                    <input type="button" value="{% trans 'Add' %}"
                                           class="btn btn-default add_line"
                                           title="{% trans 'Add Line' %}">
                                    <input type="button" value="{% trans 'Del' %}"
                                           class="btn btn-white del_line"
                                           title="{% trans 'Delete Line' %}">
                                </div>
                            </div>
                        {% endfor %}
                    {% else %}
                        <div class="form-group parcel_row">
                            <div class="col-sm-1 col-sm-offset-2">
                                <input type="text" name="variants-0-title"
                                       value=""
                                       required="" class="form-control">
                            </div>
                            <div class="col-sm-3">
                                <input type="text" name="variants-0-content"
                                       value=""
                                       class="form-control">
                            </div>
                            <div class="col-sm-1">
                                <input type="number" name="variants-0-quantity"
                                       value="{{ parcel.width|zero_default:0 }}" step="1"
                                       min="1"
                                       required="" class="form-control">
                            </div>
                            <div class="col-sm-1">
                                <input type="text" name="variants-0-sku"
                                       class="form-control">
                            </div>
                            <div class="col-sm-1">
                                <div class="dropfile visible-lg" for="select_file">
                                    <small>Click or Drag</small>
                                </div>
                                <input id="select_file" type="file" class="hidden">
                            </div>
                            <div class="col-sm-2">
                                <input type="button" value="{% trans 'Add' %}"
                                       class="btn btn-default add_line" title="{% trans 'Add Line' %}">
                                <input type="button" value="{% trans 'Del' %}"
                                       class="btn btn-white del_line" title="{% trans 'Delete Line' %}">
                            </div>
                        </div>
                    {% endif %}
                </div>
                <div class="line line-dashed line-lg pull-in"></div>
                <div class="form-group">
                    <div class="col-sm-4 col-sm-offset-2">
                        <button type="submit" name="action" value="save_variants" class="submit_edit btn btn-primary">{% trans 'Save changes' %}</button>
                        <button type="button" class="btn btn-white btn-cancel">{% trans 'Cancel' %}</button>
                    </div>
                </div>
            </form>
        </div>
    </section>
</section>
{% endblock %}
{% block custom_css %}
    <style>
    .dropfile small {
        margin: 10px 0;
        display: block;
    }
    </style>
{% endblock %}
{% block product_js %}
    <script>
        $(function () {

        });
    </script>
{% endblock %}